/*
 * Copyright (c) 2025 JShorelark Contributors
 *
 * Licensed under the same terms as the original Shorelark project.
 * See: https://github.com/patryk27/shorelark
 */
package io.jshorelark.simulation;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

import lombok.Builder;
import lombok.Value;
import lombok.With;

/**
 * Configuration for the simulation. Matches Rust's Config struct.
 *
 * @author Jose
 * @version $Id: $Id
 */
@Value
@Builder
@With
@JsonDeserialize(builder = Config.ConfigBuilder.class)
public class Config {
  /** World width. */
  @Builder.Default float worldWidth = 1.0f;

  /** World height. */
  @Builder.Default float worldHeight = 1.0f;

  /** Number of neurons in each bird's brain. */
  @Builder.Default int brainNeurons = 9;

  /** Field of view range. */
  @Builder.Default float eyeFovRange = 0.25f;

  /** Field of view angle. */
  @Builder.Default float eyeFovAngle = (float) (Math.PI + Math.PI / 4);

  /** Number of eye cells in each bird. */
  @Builder.Default int eyeCells = 9;

  /** Size of food items for collision detection. */
  @Builder.Default float foodSize = 0.01f;

  /** Size of birds for collision detection. */
  @Builder.Default float birdSize = 0.01f;

  /** Whether to reverse fitness (1 = yes, 0 = no). */
  @Builder.Default int gaReverse = 0;

  /** Mutation chance for genetic algorithm. */
  @Builder.Default float gaMutChance = 0.01f;

  /** Mutation coefficient for genetic algorithm. */
  @Builder.Default float gaMutCoeff = 0.3f;

  /** Maximum simulation speed. */
  @Builder.Default float simSpeedMax = 0.005f;

  /** Minimum simulation speed. */
  @Builder.Default float simSpeedMin = 0.001f;

  /** Speed acceleration factor. */
  @Builder.Default float simSpeedAccel = 0.2f;

  /** Rotation acceleration factor. */
  @Builder.Default float simRotationAccel = (float) (Math.PI / 2);

  /** Length of each generation in simulation steps. */
  @Builder.Default int simGenerationLength = 2500;

  /** Number of animals in the world. */
  @Builder.Default int worldAnimals = 40;

  /** Number of food items in the world. */
  @Builder.Default int worldFoods = 60;

  /**
   * Returns the default configuration.
   *
   * @return a {@link io.jshorelark.simulation.Config} object
   */
  public static Config getDefault() {
    return builder().build();
  }

  /**
   * Returns the brain topology array [eyeCells, brainNeurons, 2].
   *
   * @return an array of {@link int} objects
   */
  public int[] getBrainTopology() {
    return new int[] {eyeCells, brainNeurons, 2};
  }

  @JsonPOJOBuilder(withPrefix = "")
  public static class ConfigBuilder {
    // Builder will be generated by Lombok
  }
}
