/*
 * Copyright (c) 2025 JShorelark Contributors
 *
 * Licensed under the same terms as the original Shorelark project.
 * See: https://github.com/patryk27/shorelark
 */
package io.jshorelark.optimizer;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

import io.jshorelark.genetic.statistics.Statistics;

import lombok.Builder;
import lombok.Value;

/**
 * Statistics for an optimization run. Matches Rust's OptStatistics struct.
 *
 * @author Jose
 * @version $Id: $Id
 */
@Value
@Builder
@JsonDeserialize(builder = OptimizationStatistics.OptimizationStatisticsBuilder.class)
public class OptimizationStatistics {
  /** Minimum fitness. */
  @JsonProperty("a")
  float minFitness;

  /** Maximum fitness. */
  @JsonProperty("b")
  float maxFitness;

  /** Average fitness. */
  @JsonProperty("c")
  float avgFitness;

  /** Median fitness. */
  @JsonProperty("d")
  float medianFitness;

  /** Generation number. */
  int generation;

  /** Genetic algorithm statistics. */
  Statistics ga;

  /**
   * Creates statistics from genetic algorithm statistics.
   *
   * @param gaStats a {@link io.jshorelark.genetic.statistics.Statistics} object
   * @param generation a int
   * @return a {@link io.jshorelark.optimizer.OptimizationStatistics} object
   */
  public static OptimizationStatistics fromGaStats(Statistics gaStats, int generation) {
    return OptimizationStatistics.builder()
        .minFitness(gaStats.getMinFitness())
        .maxFitness(gaStats.getMaxFitness())
        .avgFitness(gaStats.getAvgFitness())
        .medianFitness(gaStats.getMedianFitness())
        .generation(generation)
        .ga(gaStats)
        .build();
  }

  /**
   * Converts this to a JSON string.
   *
   * @return a {@link java.lang.String} object
   */
  public String toJson() {
    return String.format(
        "{\"a\":%.2f,\"b\":%.2f,\"c\":%.2f,\"d\":%.2f}",
        minFitness, maxFitness, avgFitness, medianFitness);
  }

  @JsonPOJOBuilder(withPrefix = "")
  public static class OptimizationStatisticsBuilder {
    // Builder will be generated by Lombok
  }
}
